### ISSUE TITLE
Playground tool doesn't work for embedded studio within a Next.js App

### ISSUE THREAD

**Issue by leighkendell** [FormidableLabs/groqd#158]
Using https://github.com/sanity-io/next-sanity#next-sanitystudio to embed the studio within my Next.js application and when I attempt to import the `groqd-playground` tool I get the following error from Next.js from one of the peer dependencies you are using to render the playground:

```sh
error - ./node_modules/@uiw/react-split/esm/style/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@uiw/react-split/esm/index.js
```
The issue being that `react-split` is importing CSS itself within it's published ESM version

**Comment by gksander** [comment]
Interesting! I've got this running in an embedded Next.js application and not running into this error. Let me take a look. What version of Next.js are you running?

**Comment by gksander** [comment]
Okay, so `@uiw/react-split` is importing CSS itself, which Next.js [doesn't support](https://github.com/vercel/next.js/issues/19936) outside of the `/app` directory. `groqd-playground` works out of the box with `/app` directory, where this isn't a problem. But for `/pages` directory, the story is a bit different. Until we can remove this dependency on `@uiw/react-split`, there are basically two options (based on version of Next).

## Next.js >= 13.1

With 13.1, Next.js [started offering a `transpilePackages`](https://nextjs.org/blog/next-13-1#built-in-module-transpilation-stable) option, and you can configure it to transpile react-split:

```js
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ["@uiw/react-split"]
}
```

## Next.js < 13.1

For version of Next below 13.1, you'll likely be stuck using [`next-transpile-modules`](https://www.npmjs.com/package/next-transpile-modules) to transpile `@uiw/react-split`:

```js
const withTM = require("next-transpile-modules")(["@uiw/react-split"]);

const nextConfig = { /* ... */ };

module.exports = withTM(nextConfig);
```

## Work for the `groqd` team

I'm going to work on adding this into the documentation. I'm also going to look around to see if there's a split-pane implementation that's no-CSS so that this fundamentally isn't a limitation, or just roll our own version.

**Comment by leighkendell** [comment]
Thanks so much for the work around! And my apologies, I should have been more specific. I am on Next 13.3 and not using the app directory (as much as I’d like to!).
