### ISSUE TITLE
Schema limitations, empty array returns null

### ISSUE THREAD

**Issue by OllieJT** [FormidableLabs/groqd#4]
Thank you for creating this, I was working on something with a similar goal and a very different way of getting there.

I'm experiencing several limitations with the abstraction, namely that Qroqd doesn't include much of the Zod api. This is problematic as when querying array date with Groq, if no values are returned it defaults to null, rather than an empty array - but the Groqd abstraction only allws me to apply things like `.nullable()` and `.optional()` to primitives like `q.string().nullable()`.

This means that when working with more complex payloads that have some level of nesting, or query additional sets of data with the `q()` pipe I'm forced to eject from the "SafeQueryRunner" that implements zods strict runtime parsing.

---

Am I missing something, or am I right in thinking this is a limitation?

---

Example:

```ts

const events = q(
	'*',
	q.filter(`_type == "session"`),
	q.slice(0, 10),
	q.grab({
		attendeeCount: q.number().default(0),
		date: q.date(),
		/*
		This should in most cases return an array of dates.
		However, when no entries match the filter it returns null.
		I don't believe I have the tools to fallback to an empty array or allow null
		*/
		schedule: q('schedule', q.filter(`startAt >= now()`), q.grabOne('startAt', q.date(),)),
	}),
);

```

Possible Solutions:

1. Allow for chaining like in zod with `.nullable()`, `.optional()` etc
2. Make use of [the coalesce function in Sanity](https://www.sanity.io/docs/groq-functions#80d6f2c07a20) to enforce fallback values.

**Comment by olemagnus** [comment]
This is also a problem with empty string fields. It returns null and throws a ZodError. Having to use q.unknown() for every field that is not required isn't optimal. The optional() and default() does nothing.

**Comment by OllieJT** [comment]
> This is also a problem with empty string fields. It returns null and throws a ZodError. Having to use q.unknown() for every field that is not required isn't optimal. The optional() and default() does nothing.

This is a feature of Zod, everything is required by default... and because values default to null (not sure if that's `qroq` or `sanity`) you will need `.nullable()` rather than `.optional()`.

I've always found these methods unintuitive, but I don't believe it's an issue with this repo, rather than a behaviour of `zod` @olemagnus

**Comment by gksander** [comment]
I was out last week, and just now catching up on this. Thank you for bringing this up!

The `q.date` method is [implemented here](https://github.com/FormidableLabs/groqd/blob/f8241a982f407980618274f53b5c192e21337cde/src/index.ts#L76-L78) and looks something like:

```ts
const dateSchema = z.preprocess((arg) => {
  if (typeof arg == "string" || arg instanceof Date) return new Date(arg);
}, z.date());
```

This was mostly just to parse out date strings that would come back from Sanity. You'll also notice that the `q.string` etc. methods are mostly just shorthands for Zod methods:

```ts
pipe.string = z.string;
pipe.number = z.number;
pipe.boolean = z.boolean;
pipe.unknown = z.unknown;
```

Which allows you to do things like `q.string().nullable()` etc. (since it's really just an alias for `z.string`). 

I'll try to play around with this scenario you've got here, but we might start by just trying to just swap `q.date()` for a custom Zod schema just using Zod methods. For ease-of-use, I think it makes sense to export `z` from `groqd` as well so that it's easier to roll your own custom schemas to use in scenarios like this.

**Comment by gksander** [comment]
Okay, I re-read through this a few times, and I think I've got a better understanding of what you're running into. It sounds like the groq query is returning `schedule: null` when the `[startAt >= now()]` filter doesn't return any documents, and the `null` value is not an array. Is that correct?

And then in terms of your two potential solutions, you're thinking having `.optional()`, `.nullable()`, etc. methods on the `q()` value itself, and not particularly on the `q.date()` schema?
