### ISSUE TITLE
Expand contentBlock to allow custom fields in Markdefs 

### ISSUE THREAD

**Issue by heggemsnes** [FormidableLabs/groqd#61]
We often have an internal link field (reference) in the markDefs part of block content, as of now I can see no way to expand this from the contentBlock helper. 

Would be great to add and option to add additional fields like this: 

```typescript

body: q.array(q.contentBlock({
  markDefs: {
  link: q('internalLink')
    .deref()
    .grab({
      _id: q.string(),
      _type: q.string(),
      slug: ['slug.current', q.string()],
    })
    .nullable(),
  }
}))

```

**Comment by gksander** [comment]
You're absolutely right, this should be allowed! We should be able to get this added in without introducing any sort of breaking changes.

**Comment by gksander** [comment]
Closing this issue, as I believe this has been resolved. If not, we can reopen.

**Comment by schwartzmj** [comment]
> This doesn't seem to work @gksander, in the docs there is an example:
> 
> `markDefs: q.object({ _type: q.literal("link"), href: q.string() })`
> 
> But I'm not sure how that translates to what @heggemsnes had mentioned in the original issue. It's unclear also how this would work for multiple fields to check for different types of links for example (internal, external).
> 
> I get "Invalid input" when trying to pass anything to markDefs, and I also don't see any change to the generated query :(

Same issue here. Unless I'm misunderstanding something, this doesn't appear to work.

**Comment by jemjam** [comment]
Okay, I was considering a new issue, then I found this one. I believe what folks are looking for (or at least what I've been trying) is a way to deref fields within that object schema.

Here's a pretty straight forward example: there's this [great little sanity guide that suggests a pattern for creating internal and external links](https://www.sanity.io/guides/portable-text-internal-and-external-links), where the internal links are references to other documents. The guide [continues to suggest a query](https://www.sanity.io/guides/portable-text-internal-and-external-links#b0847aaef91a) that includes the slug from the referenced document. (My example pictured below has the `reference` (field) called `pointsTo` instead. 😅 ) They have a short breakdown of how to update your query for this to be useful, the last bullet:

> _type == "internalLink" => { "slug": @.reference->slug } If the object in markDefs is of the type “internalLink,” output a key called “slug,” _follow the reference_, and return the document’s slug.

I couldn't find a way to properly recreate this. Within groqd, the markdefs defined within that contentBody() type helper wouldn't allow me following references. You get type errors about not being able to assign a query type to a z/validator type.

![groqd-contentBlock-references](https://github.com/FormidableLabs/groqd/assets/8083892/4d0f63e9-18ad-4983-9589-ce9d3888c30b)
The type error: Type 'EntityQuery<ZodUnknown>' is missing the following properties from type 'ZodType<any, any, any>': _type, _output, _input, _def, and 30 more.(2740)

If this should work (and I'm holding it wrong) then I'm open to suggestions or alternate approaches? Otherwise, I'm just adding my notes for recreation in case anyone else stumbles down this path.

**Comment by tim-vyg** [comment]
@jemjam I have the exact same use case, I want to `deref` the page in my internal link but can't seem to dereference inside an object. Did you ever find a work around?

**Comment by tim-vyg** [comment]
Sorry just saw this and lost the train of though I was having last week but I got around it by making a custom block selection 

```
// the goats over at https://github.com/FormidableLabs/groqd/issues/185
export const contentBlockSelection = {
  _key: q.string(),
  _type: q.literal('block'),
  children: q.array(
    q.object({
      _key: q.string(),
      _type: q.string(),
      text: q.string(),
      marks: q.array(q.string()),
    }),
  ),
  markDefs: q('markDefs').filter().select(LinkSelection).nullable(),
  style: q.string().nullish(),
  listItem: q.string().nullish(),
  level: q.number().nullish(),
} satisfies Selection;

**Comment by tim-vyg** [comment]
Related to https://github.com/FormidableLabs/groqd/issues/185
